exp_tag: "error detection training"

actions:
  - train

# training actions
train:
  type: "error_detection_training"
  device: "cuda:0"
  model: "bert-base-chinese"
  train_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  dev_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/error_detection_training2"
  n_best: 15
  max_utts: 999999
  max_seq_len: 50
  batch_size: 100
  epoch: 10

# inference actions
scoring:
  type: "error_detection_training"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/error_detection_training2/checkpoint_10.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/error_detection_training2/test.lm10.json"
  max_utts: 1
  batch_size: 300

rescoring:
  dev_asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  dev_lm_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/error_detection_training2/dev.lm9.json"
  test_asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  test_lm_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/error_detection_training2/test.lm9.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/error_detection_training2/test.am_lm.json"
  max_utts: 999999