action: score

method: "bertsem"

setting:
  seed: 10
  device: "cuda:0"
  asr_data_file: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  model_file: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/sem/checkpoint_1.pth"
  output_file: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/Fohr21INTERSPEECH/sem/test.sem.json"

  preprocess:
    n_best: 15
    max_utts: 999999

  model:
    bert: "bert-base-chinese"

  dataloader:
    batch_size: 400
    num_worker: 5