action: train

method: "bertalsem"

setting:
  seed: 10
  device: "cuda:0"

  train_data_file: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  dev_data_file: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/Fohr21INTERSPEECH/alsem"

  batch_loss_rescord_step: 1000

  resume: 
    # if epoch == 1, it will start training at epoch 2
    epoch: 1
    model_weight_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/Fohr21INTERSPEECH/alsem/checkpoint_1.pth" 

  preprocess:
    n_best: 15
    max_utts: 999999
    max_seq_len: 100

  model:
    bert: "bert-base-chinese"
    lstm_hidden_size: 64
    dropout: 0.3

  dataloader:
    shuffle: True
    batch_size: 64
    num_worker: 5

  opt:
    # 0 for not freeze
    bert_freeze_epoch: 2
    lr: 0.000001
    epoch: 4
  