action: rescore

setting:
  use_score: 
    - am
    - sem

  input_files:
    dev:
      am: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
      lm: 
      sem: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/Fohr21INTERSPEECH/sem/dev.sem.json"
    test:
      am: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
      lm:
      sem: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/Fohr21INTERSPEECH/sem/test.sem.json"

  step: 1
  weight_range:
    am: 
      start: 1
      end: 1
    lm:
      start: 0
      end: 10
    sem:
      start: 0
      end: 100

  max_utts: 999999
  n_best: 15
