actions:
  - train

# training actions
train:
  type: "MLM"
  device: "cpu"
  model: "bert-base-chinese"
  train_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  dev_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training"
  n_best: 2
  max_utts: 4
  max_seq_len: 50
  batch_size: 100
  epoch: 2
  num_worker: 3

# inference actions
scoring:
  type: "PLL"
  device: "cpu"
  model: "bert-base-chinese"
  model_weight_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\checkpoint_1.pth"
  asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  n_best: 2
  max_utts: 4
  max_seq_len: 50
  batch_size: 100
  num_worker: 3

rescoring:
