actions:
  - scoring

# training actions
train:
  type: "MLM_distillation"
  device: "cpu"
  model: "bert-base-chinese"
  train_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  dev_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD"
  n_best: 1
  max_utts: 1
  max_seq_len: 50
  batch_size: 100
  epoch: 4
  num_worker: 3

# inference actions
scoring:
  type: "MLM_distillation"
  device: "cpu"
  model: "bert-base-chinese"
  model_weight_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD\\checkpoint_10.pth"
  asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD\\test.lm.json"
  n_best: 2
  max_utts: 2
  batch_size: 100
  num_worker: 3

rescoring:
  dev_asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/dev.am.json"
  dev_lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/MD/dev.lm.json"
  test_asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  test_lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/MD/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/test.am_lm.json"
  max_utts: 9999999