actions:
  - train

# training actions
train:
  type: "MLM_distillation"
  device: "cpu"
  model: "bert-base-chinese"
  train_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  dev_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD"
  n_best: 2
  max_utts: 2
  max_seq_len: 50
  batch_size: 100
  epoch: 10
  num_worker: 3

# inference actions
scoring:
  type: "sentence_level"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/checkpoint_50.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/test.lm.json"
  n_best: 2
  max_utts: 2
  max_seq_len: 50
  batch_size: 100
  epoch: 2
  num_worker: 3

rescoring:
  dev_asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  dev_lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/test.lm.json"
  test_asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  test_lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/test.am_lm.json"
  max_utts: 9999999